import pygame,os
pygame.init()
screen = pygame.display.set_mode((800,800))
pygame.display.set_caption("matchthefollowing")
screen.fill((255,255,255))
path1 = os.path.join("images","subwaysurfer.png")
path2 = os.path.join("images","ludo.png")
path3 = os.path.join("images","templerun(1).png")
path4 = os.path.join("images","candycrush.jpg")
image1 = pygame.image.load(path1)
image2 = pygame.image.load(path2)
image3 = pygame.image.load(path3)
image4 = pygame.image.load(path4)
font = pygame.font.SysFont("Arial",36)
screen.blit(image1,(200,375))
screen.blit(image2,(200,275))
screen.blit(image3,(200,175))
screen.blit(image4,(200,75))
t1 = font.render("templerun",True,(0,0,0))
t2 = font.render("ludo",True,(0,0,0))
t3 = font.render("candycrush",True,(0,0,0))
t4 = font.render("subwaysurfer",True,(0,0,0))
screen.blit(t1,(400,400))
screen.blit(t2,(400,300))
screen.blit(t3,(400,200))
screen.blit(t4,(400,100))
pygame.display.update()
while 1:
    event = pygame.event.poll()#poll retrieves 1 event at a time
    if event.type == pygame.MOUSEBUTTONDOWN:
        pos = pygame.mouse.get_pos()
        pygame.draw.circle(screen,(0,0,0),(pos),20,0)
        pygame.display.update()
    if event.type == pygame.MOUSEBUTTONUP:
        pos2 = pygame.mouse.get_pos()
        pygame.draw.line(screen,(0,0,0),(pos),(pos2),5)
        pygame.draw.circle(screen,(0,0,0),(pos2),20,0)
        pygame.display.update()