import pygame,time,os
pygame.init()
screen = pygame.display.set_mode((800,800))
pygame.display.set_caption = ("walking animation")
path1 = os.path.join("images","walk1.png")
path2 = os.path.join("images","walk2.png")
path3 = os.path.join("images","walk3.png")
path4 = os.path.join("images","walk4.png")
image1 = pygame.image.load(path1)
i1 = pygame.transform.scale(image1,(800,800))
image2 = pygame.image.load(path2)
i2 = pygame.transform.scale(image2,(800,800))
image3 = pygame.image.load(path3)
i3 = pygame.transform.scale(image3,(800,800))
image4 = pygame.image.load(path3)
i3 = pygame.transform.scale(image4,(800,800))
font1 = pygame.font.SysFont("Times New Roman",72)
font2 = pygame.font.SysFont("Arial",36)
running = True
while running:
    screen.blit(i1,(0,0))
    t1 = font1.render("",True,(0,0,0))
    screen.blit(t1,(210,180))
    pygame.display.update()
    time.sleep(0.3)
    screen.fill((255,255,255))
    screen.blit(i2,(0,0))
    t2 = font2.render("",True,(0,0,0))
    screen.blit(t2,(200,200))
    pygame.display.update()
    time.sleep(0.3)
    screen.blit(i3,(0,0))
    t3 = font2.render("",True,(0,0,0))
    screen.blit(t3,(300,300))
    pygame.display.update()
    time.sleep(0.3)
    t4 = font2.render("",True,(0,0,0))
    screen.blit(t3,(300,300))
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
pygame.quit()